name: Update events

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate events.json
        run: npm run build

      - name: Pull latest changes
        run: |
          git stash --include-untracked || true
          git pull --rebase origin main
          git stash pop || true

      - name: Commit events.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Mise à jour automatique de events.json"
